INSERT INTO manager VALUES('hpendleberry2n'); 
INSERT INTO manager VALUES('ndoersf'); 
INSERT INTO manager VALUES('smccomiskieu'); 
INSERT INTO manager VALUES('rgrimsell4e'); 
INSERT INTO manager VALUES('jalessandretti3k'); 
INSERT INTO manager VALUES('aorkney37'); 
INSERT INTO manager VALUES('ndavey1x'); 
INSERT INTO manager VALUES('bkilcullen4q'); 
INSERT INTO manager VALUES('jchasier4u'); 
INSERT INTO manager VALUES('zelsie19'); 
INSERT INTO manager VALUES('lrollett1u'); 
INSERT INTO manager VALUES('bpawellek52'); 
INSERT INTO manager VALUES('gkovnot4l'); 
INSERT INTO manager VALUES('mrestieaux26'); 
INSERT INTO manager VALUES('ayardy56'); 
INSERT INTO manager VALUES('ccraister4x'); 
INSERT INTO manager VALUES('mcosker1k'); 
INSERT INTO manager VALUES('tseneschal48'); 
INSERT INTO manager VALUES('ciannuzzelli2a'); 
INSERT INTO manager VALUES('mdoig1w'); 

SELECT *  FROM manager LIMIT 10; 